# Generated by Django 5.2.13 on 2026-05-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
